# Generated by Django 3.1.12 on 2025-09-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('enrolment_no', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
            ],
        ),
    ]
